launcher:
    name: mini
    interval: 3.0

site:
    name: cori-interactive
    image: joezuntz/txpipe

modules: txpipe

python_paths:
    - submodules/TJPCov

stages:
    - name: TXSourceSelector
    - name: TXShearCalibration
    - name: TXLensCatalogSplitter
    - name: TXSourceMaps
    - name: TXAuxiliaryMaps
    - name: TXSimpleMask
    - name: TXSourceTrueNumberDensity
    - name: TXIngestRedmagic
    - name: TXPhotozPlots
    - name: TXTracerMetadata
    - name: TXRandomCat
    - name: TXJackknifeCenters
    - name: TXTwoPoint
    - name: TXNullBlinding
    - name: TXRealGaussianCovariance
    - name: TXTwoPointTheoryReal
    - name: TXTwoPointPlots

output_dir: examples/comparison/new_output
config: examples/comparison/new_config.yml


inputs:
    # See README for paths to download these files
    shear_catalog:  /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/shear_catalog.hdf5
    photometry_catalog:  /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/photometry_catalog.hdf5
    redmagic_catalog: /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/redmagic/cosmoDC2_v1.1.4_run_redmagic_highdens.fit
    fiducial_cosmology: data/fiducial_cosmology.yml
    calibration_table:  /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/sample_cosmodc2_w10year_errors.dat


resume: True
log_dir: examples/comparison/new_logs
pipeline_log: examples/comparison/new_log.txt
