dist: bionic

language: python

python:
  # - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran-8 swig libgsl-dev
  # camb demands that the compiler be called gfortran and
  # does not cope with it being called gfortran-7. There is
  # no way to specify the name of the compiler.
  - sudo ln -s `which gfortran-8` /usr/bin/gfortran 

install:
  - pip install cffi
  - pip install -r requirements.txt
  - wget -O data.tar.gz  "https://portal.nersc.gov/cfs/lsst/txpipe/travis/small.tgz"
  - tar -zxvf data.tar.gz

cache:
  - pip: true
  - directories:
    - data/example

script:
  - ceci examples/travis/pipeline.yml
  - cat pipeline.log
