dist: bionic

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran-7 swig libgsl-dev libopenmpi-dev openmpi-bin libopenblas-dev
  - sudo ln -s `which gfortran-7` /usr/local/bin/gfortran

install:
  - pip install cffi
  - pip install --no-binary=mpi4py -r requirements.txt
  - wget -O example-ci.tar.gz  "https://portal.nersc.gov/cfs/lsst/txpipe/data/example-ci.tar.gz"
  - tar -zxvf example-ci.tar.gz

cache: pip

script:
  - ceci examples/laptop.yml
  - test -f data/example/log.txt
  - test -f data/example/outputs/summary_statistics_real.sacc
