dist: bionic

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran-7 swig libgsl-dev libopenmpi-dev openmpi-bin libopenblas-dev
  - sudo ln -s `which gfortran-7` /usr/local/bin/gfortran

install:
  - pip install cffi
  - pip install --no-binary=mpi4py -r requirements.txt
  - wget -O example.tar.gz  "https://portal.nersc.gov/cfs/lsst/txpipe/data/example.tar.gz"
  - tar -zxvf example.tar.gz

cache: pip

script:
  - pytest
  # one of the tests runs the main example yaml, generating this
  - test -f data/example/outputs/shear_xi_plus.png
  - ceci examples/laptop_redmagic_pipeline.yml
  - test -f data/example/outputs_redmagic/shear_xi_plus.png

after_failure:
  - tail -n +1 data/example/outputs/*
  - tail -n +1 data/example/outputs_redmagic/*
