dependencies:
  - pip:
    - ceci==2.0.1
    - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
    - dask-mpi>=2022.4.0
    - git+https://github.com/LSSTDESC/CLMM.git@1.14.1
    - parallel-statistics==0.13
    - sacc[all]==0.14
    - jax==0.4.27
    - jaxlib==0.4.23
    - glass==2023.7
    - git+https://github.com/beckermr/hybrideb@a3198ea5bc8175542b058e5c1289d910f05fd99d
    # we must specifically request versions of rail algorithms
    # to ensure that we get the ceci v2 versions
    - pz-rail[algos] @ git+https://github.com/LSSTDESC/RAIL@v1.0.1
    - pz-rail-astro-tools==1.0.4
    - pz-rail-base==1.0.4
    - pz-rail-bpz==1.0.1
    - pz-rail-cmnn==1.0.1
    - pz-rail-dsps==0.0.3 # no pypi release for more than 0.3
    - pz-rail-flexzboost==1.0.1
    - pz-rail-fsps==1.0.1
    - pz-rail-gpz-v1==1.0.2
    - pz-rail-lephare==0.2 # no release for ceci2 yet - cannot use
    - pz-rail-pzflow==1.0.1
    - pz-rail-sklearn==1.0.1
    - pz-rail-som==1.0.1
