channels:
  - conda-forge
dependencies:
  - astropy=6.1.*
  - camb=1.5.*
  - cosmosis=3.7.*
  - cmake
  - dask=2024.5.2
  - dm-tree=0.1.8
  - fitsio=1.2.*
  - firecrown=1.7.*
  - h5py>=3=mpi_mpich_*
  - healpy=1.16.*
  - healsparse=1.10.*
  - jax=0.4.27
  - jaxlib=0.4.23
  - jupyter=1.0.*
  - matplotlib=3.8.*
  - mpi4py>=3
  - mpich>=4.*
  - namaster=2.0.*
  - numpy=1.26.*
  - pandas>=2.0
  - psutil=5.9.*
  - pyccl=3.0.*
  - python=3.10.*
  - scikit-learn=1.5.*
  - scipy=1.13.*
  - tables-io-full=0.9.*
  - threadpoolctl=3.5.*
  - tjpcov=0.4.*
  - treecorr=5.0.*
  - pip=24.0.*
  - pygraphviz=1.13.*
  - mockmpi
  - pip:
    - ceci==2.2
    - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
    - dask-mpi>=2022.4.0
    - git+https://github.com/LSSTDESC/CLMM.git@1.14.1
    - parallel-statistics==0.13
    - sacc[all]==0.14
    - jax==0.4.27
    - jaxlib==0.4.23
    - glass==2023.7
    - git+https://github.com/beckermr/hybrideb@a3198ea5bc8175542b058e5c1289d910f05fd99d
    - pz-rail[algos]==1.1.1
    - pz-rail-base==1.1.3
