dependencies:
  - pip:
    - ceci==1.17
    - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
    - dask-mpi>=2022.4.0
    - git+https://github.com/LSSTDESC/CLMM.git@1.12.5
    - parallel-statistics==0.13
    - sacc[all]==0.14
    - jax==0.4.27
    - jaxlib==0.4.23
    - glass==2023.7
    - git+https://github.com/beckermr/hybrideb@a3198ea5bc8175542b058e5c1289d910f05fd99d
    - pz-rail[algos] @ git+https://github.com/LSSTDESC/RAIL@v1.0.0
