channels:
  - conda-forge
dependencies:
  - astropy=5.2.2
  - camb=1.4.0
  - cosmosis=2.4.1
  - dask=2023.4.1
  - dm-tree=0.1.7
  - firecrown=1.4.0
  - fitsio=1.1.8
  - h5py=3.8.0=mpi_mpich_*
  - healpy=1.16.2
  - healsparse=1.6.4
  - jax=0.4.8
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - mpi4py=3.1.4
  - mpich=4.1.1
  - numpy=1.24.3
  - pandas=1.5.3  
  - psutil=5.9.5
  - pyccl=2.6.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - tables-io-full=0.8.1
  - threadpoolctl=3.1.0
  - treecorr=4.3.3
  - pip
  # - pip:
  #   - ceci==1.13
  #   - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
  #   - git+https://github.com/joezuntz/dask-mpi@31e35759cfb03780a12ad6ffe2b82279b0fab442
  #   - healpix==2023.1.13
  #   - parallel-statistics==0.13
  #   - pz-rail[dev]==0.99.1
  #   - sacc==0.8
  #   - tjpcov==0.3.0
