channels:
  - conda-forge
dependencies:
  - astropy>5
  - camb=1.5.*
  - cosmosis>=3.6.*
  - dask>=2023.5.*
  - dm-tree=0.1.8
  - fitsio=1.2.*
  - firecrown=1.7.*
  - h5py>=3.0.*=mpi_mpich_*
  - healpy>=1.15.*
  - healsparse>=1.7.*
  - jax=0.4.27
  - jaxlib=0.4.23
  - jupyter>=1.0.0
  - matplotlib>=3.5.*
  - mpi4py>=3.1.*
  - mpich=4.2.*
  - namaster>=2.0.*
  - numpy=1.26.*
  - pandas>2.*
  - psutil>=5.*
  - pyccl>=3.0.*
  - python=3.10.*
  - scikit-learn>=1.3.*
  - scipy=1.13.*
  - tables-io-full=0.9.*
  - threadpoolctl>=3.*
  - tjpcov=0.4.*
  - treecorr>=5.0.*
  - pip>=24.0.*
  - pygraphviz>=1.*
