channels:
  - conda-forge
dependencies:
  - astropy=6.1.*
  - camb=1.5.*
  - cosmosis=3.7.*
  - dask=2024.5.2
  - dm-tree=0.1.8
  - fitsio=1.2.*
  - firecrown=1.7.*
  - h5py=3.11.*=mpi_mpich_*
  - healpy=1.16.*
  - healsparse=1.10.*
  - jax=0.4.27
  - jaxlib=0.4.23
  - jupyter=1.0.0
  - matplotlib=3.8.*
  - mpi4py=3.1.6
  - mpich=4.2.*
  - namaster=2.0.*
  - numpy=1.26.*
  - pandas=2.2.*
  - psutil=5.9.*
  - pyccl=3.0.*
  - python=3.10.*
  - scikit-learn=1.5.*
  - scipy=1.13.*
  - tables-io-full=0.9.*
  - threadpoolctl=3.5.*
  - tjpcov=0.4.*
  - treecorr=5.0.*
  - pip
