channels:
  - conda-forge
dependencies:
  - astropy=5.2.*
  - camb=1.4.*
  - cosmosis=2.4.1
  - dask=2023.4.1
  - dm-tree=0.1.7
  - firecrown=1.4.0
  - fitsio=1.1.8
  - h5py=3.8.*=mpi_mpich_*
  - healpy=1.16.*
  - healsparse=1.6.*
  - jax=0.4.14
  - jaxlib=0.4.14
  - jupyter=1.0.*
  - matplotlib=3.7.*
  - mpi4py=3.1.*
  - mpich=4.1.*
  - numpy=1.24.*
  - pandas=1.5.*
  - psutil=5.9.*
  - pyccl=2.6.*
  - python=3.10.*
  - scikit-learn=1.2.*
  - scipy=1.10.*
  - tables-io-full=0.8.*
  - threadpoolctl=3.1.*
  - treecorr=4.3.*
  - pip
  - pip:
    - ceci==1.13
    - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
    - git+https://github.com/joezuntz/dask-mpi@31e35759cfb03780a12ad6ffe2b82279b0fab442
    - git+https://github.com/LSSTDESC/CLMM.git@1.8.0
    - healpix==2023.1.13
    - parallel-statistics==0.13
    - sacc==0.8
    - tjpcov==0.3.0
    - pz-rail[dev]==0.99.1
    - pz-rail-bpz==0.1.0
    - pz-rail-astro-tools==0.0.2
    - pz-rail-base==0.0.4
    - pz-rail-dsps==0.0.2
    - pz-rail-flexzboost==0.1.1
    - pz-rail-fsps==0.0.2
    - pz-rail-gpz-v1==0.1.2
    - pz-rail-pipelines==0.1.0
    - pz-rail-pzflow==0.0.1
    - pz-rail-sklearn==0.0.1
    - pz-rail-som==0.0.2
    - glass==2023.7
