from .base import TXSourceSelectorBase
from .base import select_weak_lensing_sample, select_tomographic_weak_lensing_sample
from ..shear_calibration import AnaCalCalculator, band_variants
import numpy as np
from ceci.config import StageParameter


class TXSourceSelectorAnacal(TXSourceSelectorBase):
    """
    Source selection and tomography for AnaCal catalogs

    This selector subcallss is designed for anacal-type catalogs like those
    that DESC plans to produce for Ruin data.
    """

    name = "TXSourceSelectorAnaCal"

    config_options = {
        **TXSourceSelectorBase.config_options,
        "delta_gamma": StageParameter(
            float, 
            required=True,
            msg= "Delta gamma value for the AnaCal response calculation"
        ),
        "mask_threshold": StageParameter(float, 40, msg = "mask threshold, for when to mask objects." ),
    }

    def data_iterator(self):
        """
        This iterator returns chunks of data in dictionaries one by one.

        We call to a parent class method to do the main iteration; the work here is
        just choosing which columns to read.
        """
        
        bands = self.config["bands"]
        shear_cols = ["ra",
                      "dec",
                      "weight",
                      "mask_value",
                      "e1",
                      "e2",
                      "m00",
                      "m20",
                      "de1_dg1",
                      "de2_dg2",
                      "dm00_dg1",
                      "dm00_dg2",
                      "dm20_dg1",
                      "dm20_dg2",
                      "s2n",
                      "ds2n_dg1",
                      "ds2n_dg2",
                      "weight_dg1",
                      "weight_dg2"
                      ]
        shear_cols += band_variants(bands, "mag", "mag_err", shear_catalog_type="Anacal")

        if self.config["input_pz"]:
            shear_cols += ["mean_z"]
        elif self.config["true_z"]:
            shear_cols += ["redshift_true"]

        chunk_rows = self.config["chunk_rows"]
        return self.iterate_hdf("shear_catalog", "shear", shear_cols, chunk_rows)
    
    def setup_output(self):
        """
        Prepare the output columns for the response values generated by Anacal
        """
        outfile = super().setup_output()
        n = outfile["tomography/bin"].size
        group = outfile.create_group("response")
        group.create_dataset("R", (n, 1, 1), dtype="f")
        group.create_dataset("R_2d", (1,), dtype="f")
        return outfile

    def setup_response_calculators(self, nbin_source):
        delta_gamma = self.config["delta_gamma"]
        mask_threshold = self.config["mask_threshold"]
        calculators = [AnaCalCalculator(select_anacal_tomographic_weak_lensing_sample, delta_gamma, mask_threshold) for i in range(nbin_source)]
        calculators.append(AnaCalCalculator(select_anacal_weak_lensing_sample, delta_gamma, mask_threshold))
        return calculators
    
    def write_tomography(self, outfile, start, end, source_bin, R):
        super().write_tomography(outfile, start, end, source_bin, R)
        group = outfile["response"]
        group["R"][start:end] = R

def select_anacal_weak_lensing_sample(data, config, calling_from_select=False):
    s2n_cut = config["s2n_cut"]
    verbose = config["verbose"]

    flag = data["mask_value"] < config["mask_threshold"]
    s2n = data["s2n"]

    n0 = len(flag)
    sel = flag
    f1 = sel.sum() / n0

    sel &= s2n > s2n_cut
    f2 = sel.sum() / n0

    sel &= data["zbin"] >= 0
    f3 = sel.sum() / n0

    if verbose and calling_from_select:
        print(f"Tomo selection {f1:.2%} flag, {f2:.2%} SNR, ", end ="")
    elif verbose:
        print(f"2D selection {f1:.2%} flag, {f2:.2%} SNR, {f3:.2%} any z bin")
        print("total 2D", sel.sum())
    return sel

def select_anacal_tomographic_weak_lensing_sample(data, config, bin_index):
    zbin = data["zbin"]
    sel = select_anacal_weak_lensing_sample(data, config, calling_from_select=True)
    sel &= zbin == bin_index
    return sel
