from .base import TXSourceSelectorBase, BinStats
from ..utils.calibrators import MetaCalibrator
from ..utils.calibration_tools import metacal_variants, MetacalCalculator, band_variants
import numpy as np
from ceci.config import StageParameter


class TXSourceSelectorMetacal(TXSourceSelectorBase):
    """
    Source selection and tomography for metacal catalogs

    This selector subclass is designed for metacal-type catalogs like those
    used in Dark Energy Survey Y1 and Y3 data releases. In DESC they are
    superseded by MetaDetect, see below.
    """

    name = "TXSourceSelectorMetacal"

    # add one option to the base class configuration
    config_options = {
        **TXSourceSelectorBase.config_options,
        "delta_gamma": StageParameter(
            float,
            required=True,
            msg="Delta gamma value for metacal response calculation",
        ),
        "use_diagonal_response": StageParameter(
            bool,
            False,
            msg="Whether to use only diagonal elements of the response matrix",
        ),
    }

    # The main differences between the classes are to do with how the data is read
    # and what output response values are generated.
    def data_iterator(self):
        """
        This iterator returns chunks of data in dictionaries one by one.

        We call to a parent class method to do the main iteration; the work here is
        just choosing which columns to read.
        """
        bands = self.config["bands"]
        shear_cols = metacal_variants("mcal_T", "mcal_s2n", "mcal_g1", "mcal_g2", "mcal_flags", "weight")
        shear_cols += ["ra", "dec", "mcal_psf_T_mean"]
        shear_cols += band_variants(bands, "mcal_mag", "mcal_mag_err", shear_catalog_type="metacal")

        if self.config["input_pz"]:
            shear_cols += metacal_variants("mean_z")
        elif self.config["true_z"]:
            shear_cols += ["redshift_true"]

        chunk_rows = self.config["chunk_rows"]
        return self.iterate_hdf("shear_catalog", "shear", shear_cols, chunk_rows)

    def setup_output(self):
        """
        Prepare the output columns for the response values generated by metacal.
        We save:

            R_gamma: the per-object estimator response
            R_S: the per-bin selection response
            R_gamma_mean: the mean per-bin estimator response
            R_total: the complete per-bin response

        and the 2D versions of the per-bin values.
        """
        # This call to the super-class method defined above sets up most of the output
        # here, so the rest of this method only does things specific to this
        # calibration scheme
        outfile = super().setup_output()
        n = outfile["tomography/bin"].size
        nbin_source = outfile["counts/counts"].size
        group = outfile.create_group("response")
        group.create_dataset("R_gamma", (n, 2, 2), dtype="f")
        group.create_dataset("R_S", (nbin_source, 2, 2), dtype="f")
        group.create_dataset("R_gamma_mean", (nbin_source, 2, 2), dtype="f")
        group.create_dataset("R_total", (nbin_source, 2, 2), dtype="f")
        group.create_dataset("R_S_2d", (2, 2), dtype="f")
        group.create_dataset("R_gamma_mean_2d", (2, 2), dtype="f")
        group.create_dataset("R_total_2d", (2, 2), dtype="f")
        return outfile

    def setup_response_calculators(self, nbin_source):
        delta_gamma = self.config["delta_gamma"]
        use_diagonal_response = self.config["use_diagonal_response"]
        calculators = [MetacalCalculator(self.select, delta_gamma, use_diagonal_response) for i in range(nbin_source)]
        calculators.append(MetacalCalculator(self.select_2d, delta_gamma, use_diagonal_response))
        return calculators

    def write_tomography(self, outfile, start, end, source_bin, R):
        # This write the per-object response values as well in addition
        # to the general values that are written in the base class.
        super().write_tomography(outfile, start, end, source_bin, R)
        group = outfile["response"]
        group["R_gamma"][start:end, :, :] = R

    def compute_per_object_response(self, data):
        delta_gamma = self.config["delta_gamma"]
        n = data["mcal_g1_1p"].size
        R = np.zeros((n, 2, 2))
        R[:, 0, 0] = (data["mcal_g1_1p"] - data["mcal_g1_1m"]) / delta_gamma
        R[:, 0, 1] = (data["mcal_g1_2p"] - data["mcal_g1_2m"]) / delta_gamma
        R[:, 1, 0] = (data["mcal_g2_1p"] - data["mcal_g2_1m"]) / delta_gamma
        R[:, 1, 1] = (data["mcal_g2_2p"] - data["mcal_g2_2m"]) / delta_gamma
        return R

    def apply_simple_redshift_cut(self, data):
        # If we have the truth pz then we just need to do the binning once,
        # as in the parent class
        if self.config["true_z"]:
            return super().apply_simple_redshift_cut(data)

        # Otherwise we have to do it once for each variant, because
        # we are using a point estimate and should have different
        # values of it for each shear.

        pz_data = {}
        variants = ["", "_1p", "_2p", "_1m", "_2m"]
        for v in variants:
            zz = data[f"mean_z{v}"]

            pz_data_v = np.zeros(len(zz), dtype=int) - 1
            for zi in range(len(self.config["source_zbin_edges"]) - 1):
                mask_zbin = (zz >= self.config["source_zbin_edges"][zi]) & (
                    zz < self.config["source_zbin_edges"][zi + 1]
                )
                pz_data_v[mask_zbin] = zi

            pz_data[f"zbin{v}"] = pz_data_v

        return pz_data

    def compute_output_stats(self, calculator, mean, variance):
        """
        Collect the per-bin response values, and the shear means and variances.
        These are calculated in a distributed way across different processes,
        so here we bring them together.

        We collate these into a BinStats object for clarity.
        """
        R, S, N, Neff = calculator.collect(self.comm, allgather=True)
        calibrator = MetaCalibrator(R, S, mean, mu_is_calibrated=False)
        mean_e = calibrator.mu.copy()

        Rtot = R + S
        P = np.diag(np.linalg.inv(Rtot @ Rtot))

        # Apply to the variances to get sigma_e
        sigma_e = np.sqrt(0.5 * P @ variance)

        # In metacal all weights are unity, so the effective N is the same
        # as the raw N.
        return BinStats(N, Neff, mean_e, sigma_e, calibrator)
