som_deepdeep_estimator:
  output_mode: default
  chunk_size: 10000
  hdf5_groupname: 'shear/ns'
  zbins_min: &id010 0.0 
  zbins_max: &id011 3.0
  zbins_dz: &id012 0.02
  calculated_point_estimates: &id001 []
  recompute_point_estimates: false
  redshift_col: &id017 z
  inputs: &id002
  - flux_r
  - flux_i
  - flux_z
  input_errs: &id003
  - flux_err_r
  - flux_err_i
  - flux_err_z
  zero_points: &id004
  - 31.4
  - 31.4
  - 31.4
  som_shape: &id005
  - 32
  - 32
  som_minerror: 0.001
  som_wrap: &id013 false
  som_take_log: &id014 true
  convert_to_flux: &id015 false
  set_threshold: true
  thresh_val: 1.0e-05
  debug: &id016 false
  name: som_deepdeep_estimator

  # model: model_deep.pkl
  # data: /sdf/home/z/zhzhuoqi/rubin-user/DP2/DP2_test_WZ/mdet_catalog.hdf5
  
  thresh_val_err: 1.0e-05
  config: null
som_deepspec_estimator:
  output_mode: default
  chunk_size: 10000
  hdf5_groupname: ''
  zbins_min: *id010
  zbins_max: *id011
  zbins_dz: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id017
  inputs: *id002
  input_errs: *id003
  zero_points: *id004
  som_shape: *id005
  som_minerror: 0.001
  som_wrap: *id013
  som_take_log: *id014
  convert_to_flux: *id015
  set_threshold: true
  thresh_val: 1.0e-05
  debug: *id016
  name: som_deepspec_estimator
  
  # model: model_deep.pkl
  # data: /sdf/home/z/zhzhuoqi/rubin-user/DP2/DP2_test_WZ/mdet_redshift_for_sompz.hdf5
  
  thresh_val_err: 1.0e-05
  config: null
som_pzc_stage:
  output_mode: default
  chunk_size: 10000
  hdf5_groupname: ''
  zbins_min: *id010
  zbins_max: *id011
  zbins_dz: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id017
  deep_groupname: ''
  name: som_pzc_stage
  pz_c: pz_c.hdf5
  config: null
sompz_tomobin_and_nz_onesom_binning4:
  output_mode: default
  chunk_size: 10000
  hdf5_groupname: ''
  zbins_min: *id010
  zbins_max: *id011
  zbins_dz: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id017
  make_equal_occ_bins: false
  bin_edges:
  - 0.4
  - 0.6
  - 0.8
  - 2.0
  som_shape: *id005
  name: sompz_tomobin_and_nz_onesom_binning4
  tomo_bins_wide: tomo_bins_wide_binning4.hdf5
  bhat_for_wide_data: bhat_for_wide_data_binning4.hdf5
  nz: NZ_ESTIMATED_binning4.hdf5
sompz_tomobin_and_nz_onesom_binning5:
  output_mode: default
  chunk_size: 10000
  hdf5_groupname: ''
  zbins_min: *id010
  zbins_max: *id011
  zbins_dz: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id017
  make_equal_occ_bins: false
  bin_edges:
  - 0.1
  - 0.4
  - 0.6
  - 0.8
  - 9999.9
  som_shape: *id005
  name: sompz_tomobin_and_nz_onesom_binning5
  tomo_bins_wide: tomo_bins_wide_binning5.hdf5
  bhat_for_wide_data: bhat_for_wide_data_binning5.hdf5
  nz: NZ_ESTIMATED_binning5.hdf5
  
som_deep_informer_big:
  output_mode: default
  redshift_col: z
  hdf5_groupname: ''
  inputs:
  - flux_r
  - flux_i
  - flux_z
  input_errs:
  - flux_err_r
  - flux_err_i
  - flux_err_z
  zero_points:
  - 31.4
  - 31.4
  - 31.4
  som_shape: [32, 32]
  som_minerror: 0.001
  som_wrap: false
  som_take_log: true
  convert_to_flux: false
  set_threshold: true
  thresh_val: 1.0e-05
  thresh_val_err: 1.0e-05
  name: som_deep_informer_big
  # model: model_deep.pkl
  # config: null