launcher:
    name: mini
    interval: 1.0

# These site options tell the launcher to use shifter
site:
    name: cori-interactive
    image: joezuntz/txpipe
    volume: ${PWD}:/opt/txpipe

modules: txpipe


stages:
    - name: CMIngestHalosCosmoDC2
    - name: CMSelectHalos
    - name: CMSelectBackground
    - name: CMRandoms
      nprocess: 16
      nodes: 4
    - name: TXJackknifeCenters
    - name: CMRedshifts
    - name: CMCorrelations
      nprocess: 4
      nodes: 4
      threads_per_process: 64
    - name: CMCorrelationsPlot


output_dir: data/cluster_mag_skysim/outputs

config: examples/cluster_mag/cluster_mag_skysim_config.yml




inputs:
    photometry_catalog: /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/skysim5000_v1.1.1/photometry_catalog.hdf5

resume: True
log_dir: data/cluster_mag_skysim/logs
pipeline_log: data/cluster_mag_skysim/log.txt

