launcher:
    name: mini
    interval: 1.0

# These site options tell the launcher to use shifter
site:
    name: cc-parallel
    image: txpipe_latest.sif
    volume: ${PWD}:/opt/TXPipe

modules: txpipe


stages:
#    - name: CMIngestHalosCosmoDC2
    - name: CMSelectHalos
      nprocess: 16
      nodes: 1
    - name: CMSelectBackground
      nprocess: 16
      nodes: 1
    - name: CMRandoms
      nprocess: 16
      nodes: 1
    - name: TXJackknifeCenters
    - name: CMCorrelations
      nprocess: 2
      threads_per_process: 16
    - name: CMCorrelationsPlot


output_dir: data/cluster_mag/outputs
config: examples/cluster_mag/cluster_mag_config.yml

inputs:
    photometry_catalog: /pbs/throng/lsst/users/jzuntz/cluster_mag/from_nersc/photometry_catalog.hdf5
    cluster_mag_halo_catalog: /pbs/throng/lsst/users/jzuntz/cluster_mag/from_nersc//cluster_mag_halo_catalog.hdf5


resume: True
log_dir: data/cluster_mag/logs
pipeline_log: data/cluster_mag/log.txt

