CMIngestHalosCosmoDC2:
    cat_name: skysim5000_v1.1.1
    halo_mass_min: 0.5e+13
    initial_size: 1_000_000
    chunk_rows: 10_000_000
    ra_range: [-1000, 1000.]
    dec_range: [-1000.0, 1000.0]

CMSelectBackground:
    ra_range: [-1000., 1000.0]
    dec_range: [-1000.0, 1000.0]
    mag_cut: 26.0
    zmin: 1.5
    nside: 2048
    initial_size: 1_000_000
    chunk_rows: 10_000_000

CMSelectHalos:
    zedge: [0.2, 0.4, 0.6, 0.8, 1.0, 1.2]
    medge: [20, 30, 45, 70, 120, 220]
    initial_size: 100_000
    chunk_rows: 10_000_000

CMRandoms:
    density: 1.


TXJackKnife:
    npatch : 64
    every_nth: 100


CMCorrelations:
    min_sep: 0.5
    max_sep: 300.
    nbins: 9
    bin_slop: 0.1
    sep_units: arcmin
    verbose: 1
    var_method': jackknife

# no options for this one
CMCorrelationsPlot: {}
