global:
    chunk_rows: 1000000
    pixelization: healpix
    nside: 2048
    sparse: true


BPZliteInformer:
    zmin: 0.0
    zmax: 3.0
    nzbins: 301
    columns_file: ./data/bpz_ugrizy.columns
    data_path: ./data/example/rail-bpz-inputs
    spectra_file: CWWSB4.list
    prior_band: i
    ref_band: i
    # Not sure about this
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    mag_err_min: 0.005
    inform_options: {save_train: false, load_model: false, modelfile: BPZpriormodel.out}
    madau_reddening: no
    bands: riz
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    hdf5_groupname: photometry




BPZliteEstimator:
    zmin: 0.0
    zmax: 3.0
    dz: 0.01
    nzbins: 301
    data_path: ./data/example/rail-bpz-inputs
    band_names: [mag_u, mag_g, mag_r, mag_i, mag_z, mag_y]
    bands: [mag_u, mag_g, mag_r, mag_i, mag_z, mag_y]
    band_err_names: [mag_err_u, mag_err_g, mag_err_r, mag_err_i, mag_err_z, mag_err_y]
    err_bands: [mag_err_u, mag_err_g, mag_err_r, mag_err_i, mag_err_z, mag_err_y]
    hdf5_groupname: photometry
    nondetect_val: .inf
    unobserved_val: .nan
    columns_file: ./data/bpz_ugrizy.columns
    spectra_file: CWWSB4.list
    prior_band: mag_i
    ref_band: mag_i
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    mag_err_min: 0.005
    madau_reddening: false
    mag_limits:
        mag_u: 27.79
        mag_g: 29.04
        mag_r: 29.06
        mag_i: 28.62
        mag_z: 27.98
        mag_y: 27.05



TXSourceSelectorSimple:
    input_pz: false
    true_z: false
    bands: ugrizy
    T_cut: 0.5
    s2n_cut: 10.0
    source_zbin_edges: [0.5, 0.7, 0.9, 1.1, 2.0]
    shear_prefix: ''
    spec_mag_column_format: "{band}_cModelMag"
    spec_redshift_column: redshift


TXRandomForestLensSelector:
    verbose: true
    bands: ugrizy
    lens_zbin_edges: [0.1, 0.4, 0.6, 0.8, 1.0, 1.2]
    random_seed: 12344
    mag_i_limit: 24.1
    selection_type: maglim
    spec_mag_column_format: "{band}_cModelMag"
    spec_redshift_column: redshift

TXPhotozSourceStack:
    classname: TXPhotozStack
    name: TXPhotozSourceStack

TXPhotozLensStack:
    classname: TXPhotozStack
    name: TXPhotozLensStack

TXPhotozPlotSource:
    name: TXPhotozPlotSource

TXPhotozPlotLens:
    name: TXPhotozPlotLens

TXTwoPoint:
    do_shear_shear: false
    do_shear_pos: false
    do_pos_pos: true
    nbins: 10
    verbose: 1
    subtract_mean_shear: true


IngestEDFS:
    name: IngestEDFS
    select_field: EDFS

IngestECDFS:
    name: IngestECDFS
    select_field: ECDFS

IngestLGLF:
    name: IngestLGLF
    select_field: LGLF

TXIngestDataPreview1:
    name: TXIngestDataPreview1
    cosmology_tracts_only: true

TXRandomCat:
    density: 10 # gals per sq arcmin


TXTwoPointFourier:
    flip_g2: true
    ell_min: 200
    ell_max: 2200
    bandwidth: 200
    cache_dir: ./cache/workspaces
    do_shear_shear: false
    do_shear_pos: false
    do_pos_pos: true
    compute_theory: true
