# Values in this section are accessible to all the different stages.
# They can be overridden by individual stages though.
global:
    # This is read by many stages that read complete
    # catalog data, and tells them how many rows to read
    # at once
    chunk_rows: 100000
    # These mapping options are also read by a range of stages
    pixelization: healpix
    nside: 512
    sparse: True  # Generate sparse maps - faster if using small areas


TXTruthLensSelector:
    # Mag cuts
    input_pz: False
    true_z: True
    lens_zbin_edges: [0.1, 0.3, 0.5]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

TXDirectCalibrationLens:
    n_neighbors: 100

TXDirectCalibrationSource:
    bands: riz

TXSourceSelectorMetadetect:
    input_pz: False
    true_z: True
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.5, 0.7, 0.9, 1.1, 2.0]
    shear_prefix: ""
    true_z: False
