global:
    chunk_rows: 1000000
    pixelization: healpix
    nside: 256
    sparse: true

BPZliteInformer:
    zmin: 0.0
    zmax: 3.0
    nzbins: 301
    columns_file: ./data/bpz_ugrizy.columns
    data_path: ./data/example/rail-bpz-inputs
    spectra_file: SED/CWWSB4.list
    prior_band: i
    # Not sure about this
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    mag_err_min: 0.005
    inform_options: {save_train: false, load_model: false, modelfile: BPZpriormodel.out}
    madau_reddening: no
    bands: riz
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    hdf5_groupname: photometry


BPZ_lite:
    zmin: 0.0
    zmax: 3.0
    dz: 0.01
    nzbins: 301
    data_path: ./data/example/rail-bpz-inputs
    band_names: [mag_u, mag_g, mag_r, mag_i, mag_z, mag_y]
    band_err_names: [mag_err_u, mag_err_g, mag_err_r, mag_err_i, mag_err_z, mag_err_y]
    hdf5_groupname: photometry
    nondetect_val: .inf
    unobserved_val: .nan
    columns_file: ./data/bpz_ugrizy.columns
    spectra_file: SED/CWWSB4.list
    prior_band: mag_i
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    mag_err_min: 0.005
    madau_reddening: false
    mag_limits:
        mag_u: 27.79
        mag_g: 29.04
        mag_r: 29.06
        mag_i: 28.62
        mag_z: 27.98
        mag_y: 27.05


TXMeanLensSelector:
    lens_zbin_edges: [0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
    selection_type: maglim
    maglim_limit: 24.0

TXLensCatalogSplitter: {}
TXSourceSelectorHSC:
    bands: ugrizy
    verbose: true
    T_cut: 1.3
    s2n_cut: 10.0
    source_zbin_edges: [0.3, 0.5, 0.7, 0.9]
    shear_prefix: ''
    max_shear_cut: 10.0

TXShearCalibration: {}


TXPhotozSourceStack: {}
TXPhotozLensStack: {}
TXSourceMaps: {}
TXLensMaps: {}

TXAuxiliarySourceMaps: {}

TXAuxiliaryLensMaps: {}

TXSimpleMask: {}

TXTracerMetadata: {}

TXRandomCat:
    method: spherical_projection
TXJackknifeCenters:
    npatch: 100

TXTwoPoint:
    flip_g2: true
    min_sep: 2.5
    max_sep: 250.0
    nbins: 20
    verbose: 1


#TXRealGaussianCovariance:

TXTwoPointPlotsTheory: {}
