# Stages to run
stages:
    - name: Inform_BPZ_lite
    - name: BPZ_lite
    - name: TXShearCalibration
    - name: TXMeanLensSelector
    - name: TXLensCatalogSplitter
    - name: TXSourceSelectorHSC
    - name: TXPhotozSourceStack
    - name: TXPhotozLensStack
    - name: TXMainMaps
    - name: TXAuxiliarySourceMaps  # make PSF and flag maps
    - name: TXAuxiliaryLensMaps    # make depth and bright object maps
    - name: TXSimpleMask         # combine maps to make a simple mask
    - name: TXTracerMetadata     # collate metadata
    - name: TXRandomCat          # generate lens bin random catalogs
    - name: TXJackknifeCenters   # Split the area into jackknife regions
    - name: TXTwoPoint           # Compute real-space 2-point correlations
      threads_per_process: 2
 
# Where to put outputs
output_dir: data/dp0.2/outputs

# How to run the pipeline: mini, parsl, or cwl
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2

# modules and packages to import that have pipeline
# stages defined in them
modules: txpipe rail.stages

# where to find any modules that are not in this repo,
# and any other code we need.
python_paths: []

# configuration settings
config: examples/dp0.2/config.yml


inputs:
    # See README for paths to download these files
    spectroscopic_catalog: data/example/inputs/mock_spectroscopic_catalog.hdf5
    shear_catalog: data/dp0.2/shear_catalog.hdf5
    photometry_catalog: data/dp0.2/photometry_catalog.hdf5
    calibration_table: data/example/inputs/sample_cosmodc2_w10year_errors.dat
    fiducial_cosmology: data/fiducial_cosmology.yml

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: True
# where to put output logs for individual stages
log_dir: data/example/logs_lensfit
# where to put an overall parsl pipeline log
pipeline_log: data/example/log.txt