# Stages to run
stages:

  - name: TXDiagnosticQuantiles
  - name: TXSourceDiagnosticPlots      # Make a suite of diagnostic plots
    nprocess: 2
  - name: TXLensDiagnosticPlots      # Make a suite of diagnostic plots
  - name: TXGammaTFieldCenters   # Compute and plot gamma_t around center points
    threads_per_process: 2
  - name: TXGammaTStars    # Compute and plot gamma_t around bright stars
    threads_per_process: 2
  - name: TXGammaTRandoms        # Compute and plot gamma_t around randoms
    threads_per_process: 2
  - name: TXRoweStatistics       # Compute and plot Rowe statistics
    threads_per_process: 2
  - name: TXGalaxyStarDensity    # Compute and plot the star-galaxy density cross-correlation
  - name: TXGalaxyStarShear      # Compute and plot the star-galaxy shear cross-correlation
  - name: TXPSFDiagnostics       # Compute and plots other PSF diagnostics
  - name: TXTauStatistics        # Compute and plot the tau statistics
  - name: TXBrighterFatterPlot   # Make plots tracking the brighter-fatter effect


# modules and packages to import that have pipeline
# stages defined in them
modules: >
    txpipe
    txpipe.extensions
    txpipe.extensions.hos.fsb
    rail.creation.degraders.grid_selection
    rail.creation.engines.flowEngine
    rail.estimation.algos.nz_dir
    rail.estimation.algos.bpz_lite

# where to find any modules that are not in this repo,
# and any other code we need.
python_paths:
  - submodules/WLMassMap/python/desc/
  - submodules/pyfsb

# Where to put outputs
output_dir: data/example/outputs_metadetect

# How to run the pipeline: mini, parsl, or cwl
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2

# configuration settings
config: examples/metadetect/config.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: data/example/inputs/metadetect_shear_catalog.hdf5
    photometry_catalog: data/example/inputs/photometry_catalog.hdf5
    exposures: data/example/inputs/exposures.hdf5
    star_catalog: data/example/inputs/star_catalog.hdf5
    # This file comes with the code
    fiducial_cosmology: data/fiducial_cosmology.yml
    # For the self-calibration extension if we are not using random_catalog_source for now
    # So it is set to Null, so the yaml intepreter returns a None value to python. OBS 
    # the binned_random_catalog_source should also be set to Null in this case.
    binned_random_catalog_source: None
    flow: data/example/inputs/example_flow.pkl

    # files generated by earlier pz stages
    binned_shear_catalog: data/example/outputs_metadetect/binned_shear_catalog.hdf5
    shear_tomography_catalog: data/example/outputs_metadetect/shear_tomography_catalog.hdf5
    mask: data/example/outputs_metadetect/mask.hdf5
    lens_tomography_catalog: data/example/outputs_metadetect/lens_tomography_catalog.hdf5
    aux_lens_maps: data/example/outputs_metadetect/aux_lens_maps.hdf5
    lens_photoz_stack: data/example/outputs_metadetect/lens_photoz_stack.hdf5

    # files generated by earlier prep stages
    shear_photoz_stack: data/example/outputs_metadetect/shear_photoz_stack.hdf5
    random_cats: data/example/outputs_metadetect/random_cats.hdf5
    patch_centers: data/example/outputs_metadetect/patch_centers.txt
    tracer_metadata: data/example/outputs_metadetect/tracer_metadata.hdf5
    binned_star_catalog: data/example/outputs_metadetect/binned_star_catalog.hdf5
    binned_random_catalog: data/example/outputs_metadetect/binned_random_catalog.hdf5



# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: true
# where to put output logs for individual stages
log_dir: data/example/logs_metadetect
# where to put an overall parsl pipeline log
pipeline_log: data/example/log.txt
