# Stages to run
stages:

  - name: TXStarCatalogSplitter    # Split the star catalog into separate bins (psf/non-psf)
  - name: TXSourceMaps             # make source g1 and g2 maps
  - name: TXAuxiliarySourceMaps    # make PSF and flag maps
  - name: TXSourceNoiseMaps      # Compute shear noise using rotations

  - name: TXLensMaps               # make source lens and n_gal maps
  - name: TXLensNoiseMaps        # Compute lens noise using half-splits
  - name: TXDensityMaps          # turn mask and ngal maps into overdensity maps
  - name: TXRandomCat            # generate lens bin random catalogs

  - name: TXMapPlots             # make pictures of all the maps
  - name: TXTracerMetadata       # collate metadata
  - name: TXJackknifeCenters     # Split the area into jackknife regions

# modules and packages to import that have pipeline
# stages defined in them
modules: >
    txpipe
    txpipe.extensions
    txpipe.extensions.hos.fsb
    rail.creation.degraders.grid_selection
    rail.creation.engines.flowEngine
    rail.estimation.algos.nz_dir
    rail.estimation.algos.bpz_lite

# where to find any modules that are not in this repo,
# and any other code we need.
python_paths:
  - submodules/WLMassMap/python/desc/
  - submodules/pyfsb

# Where to put outputs
output_dir: data/example/outputs_metadetect

# How to run the pipeline: mini, parsl, or cwl
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2

# configuration settings
config: examples/metadetect/config.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: data/example/inputs/metadetect_shear_catalog.hdf5
    photometry_catalog: data/example/inputs/photometry_catalog.hdf5
    exposures: data/example/inputs/exposures.hdf5
    star_catalog: data/example/inputs/star_catalog.hdf5
    # This file comes with the code
    fiducial_cosmology: data/fiducial_cosmology.yml
    # For the self-calibration extension if we are not using random_catalog_source for now
    # So it is set to Null, so the yaml intepreter returns a None value to python. OBS 
    # the binned_random_catalog_source should also be set to Null in this case.
    binned_random_catalog_source: None
    flow: data/example/inputs/example_flow.pkl

    # files generated by earlier stages
    binned_shear_catalog: data/example/outputs_metadetect/binned_shear_catalog.hdf5
    shear_tomography_catalog: data/example/outputs_metadetect/shear_tomography_catalog.hdf5
    mask: data/example/outputs_metadetect/mask.hdf5
    lens_tomography_catalog: data/example/outputs_metadetect/lens_tomography_catalog.hdf5
    aux_lens_maps: data/example/outputs_metadetect/aux_lens_maps.hdf5
    lens_photoz_stack: data/example/outputs_metadetect/lens_photoz_stack.hdf5


# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: true
# where to put output logs for individual stages
log_dir: data/example/logs_metadetect
# where to put an overall parsl pipeline log
pipeline_log: data/example/log.txt
