#!/usr/bin/bash
#SBATCH --time=02:00:00
#SBATCH --partition=hpc,lsst
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=1
#SBATCH --mem=128000

module load conda
#source /pbs/throng/lsst/software/desc/common/miniconda/setup_current_python.sh
conda activate /sps/lsst/groups/clusters/cl_pipeline_project/conda_envs/txpipe_clp
export HDF5_DO_MPI_FILE_SYNC=0
export PYTHONPATH=/sps/lsst/users/ebarroso/TXPipe:$PYTHONPATH
ceci CLClusterReducedShear-20deg2-CL.yml 

#source ./conda/bin/activate
#export HDF5_DO_MPI_FILE_SYNC=0
#ceci examples/cosmodc2/Cluster_pipelines/pipeline-20deg2-CL-in2p3.yml
