global:
    metacalibration: True
CLClusterSACC:
    survey_name: 'cosmodc2-440deg2-CL'
    area: 440.0
TXSourceSelectorMetadetect:
    input_pz: false
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.1, 3.0]
    chunk_rows: 100000
    true_z: false
    shear_prefix: ''
CLClusterBinningRedshiftRichness:
    zedge: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1]
    richedge: [20., 35., 70., 100., 200.]

CLClusterShearCatalogs:
    chunk_rows: 100_000  # rows to read at once from source cat
    max_radius: 5   # Mpc
    delta_z: 0.2   # redshift buffer
    redshift_cut_criterion: ztrue
    redshift_weight_criterion: ztrue
    redshift_cut_criterion_pdf_fraction: 0.9
    subtract_mean_shear: false
    coordinate_system: celestial #euclidean or celestial
    use_true_shear: False


CLClusterEnsembleProfiles:
    #radial bin definition
    r_min: 0.5  #in Mpc
    r_max: 4.49840619  #in Mpc
    nbins: 11  # number of bins
    #type of profile
    delta_sigma_profile: true
    shear_profile: false
    magnification_profile: false
    coordinate_system: celestial #euclidean or celestial









