# Stages to run
stages:
  - name: TXIngestFlagshipMasks
  - name: TXIngestFlagshipMocks
  - name: TXDESIJointMask
  - name: TXCutShearCatalog
  - name: TXSourceSelectorSimple
    aliases:
      shear_catalog: cut_shear_catalog
  - name: TXShearCalibration
    aliases:
      shear_catalog: cut_shear_catalog
  - name: TXSourceMaps
  - name: TXMapPlots
    aliases:
      density_maps: none
      aux_source_maps: none
      aux_lens_maps: none
      lens_maps: none
  - name: TXUniformDepthMap
  - name: TXRandomCat
  - name: TXTracerMetadata
    aliases:
      shear_catalog: cut_shear_catalog
  - name: TXDeltaSigma
  - name: TXDeltaSigmaTheory
  - name: TXDeltaSigmaPlots
  - name: TXSourceTomography
  - name: TXTruePhotozStackSource
    classname: TXTruePhotozStack
    aliases:
      tomography_catalog: shear_tomography_catalog
      catalog: cut_shear_catalog
      weights_catalog: cut_shear_catalog
      photoz_stack: shear_photoz_stack
  - name: TXDESIMultiMockSelector
  - name: TXIngestDESI
  - name: TXPhotozPlotSource          # Plot the bin n(z)
    classname: TXPhotozPlot
    aliases:
      photoz_stack: shear_photoz_stack
      nz_plot: nz_source
  - name: TXPhotozPlotLens          # Plot the bin n(z)
    classname: TXPhotozPlot
    aliases:
        photoz_stack: lens_photoz_stack
        nz_plot: nz_lens

# Where to put outputs
output_dir: data/example/outputs_desi_mocks

# How to run the pipeline: mini, parsl, or cwl
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2

# modules and packages to import that have pipeline
# stages defined in them
modules: txpipe

# where to find any modules that are not in this repo,
# and any other code we need.
python_paths:
  - submodules/WLMassMap/python/desc/

# configuration settings
config: examples/desi_mocks/config.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    # shear_catalog: data/example/inputs/shear_catalog.hdf5
    # photometry_catalog: data/example/inputs/photometry_catalog.hdf5
    # photoz_trained_model: data/example/inputs/cosmoDC2_trees_i25.3.npy
    # exposures: data/example/inputs/exposures.hdf5
    # star_catalog: data/example/inputs/star_catalog.hdf5
    # desi_catalog: /scratch/gpfs/AAMON/desc_analysis/catalogs/output_select_lsst_obs_cond_dp2_DESI_ELG_flagship.pq
    # mask should be already a combination of source and lens.
    # mask: /scratch/gpfs/AAMON/desc_analysis/catalogs/dp2_23p5_combined_mask_nmin=500_nside=512.hdf5 # /scratch/gpfs/AAMON/desc_analysis/catalogs/mask_eg.fits
    # This file comes with the code
    fiducial_cosmology: data/fiducial_cosmology.yml
    spectroscopic_catalog: data/example/inputs/mock_spectroscopic_catalog.hdf5
    # desi_mask:
    #     name: desi_dr1_mask
    # original_dp2_mask: /global/cfs/cdirs/lsst/groups/PZ/users/qhang/dp2_maps_may/dp2_public_catalog_mask_nside-256.fits
    shear_mask: "/global/cfs/cdirs/lsst/groups/PZ/users/qhang/flagship_dp2/flagship_mock/mask_flagship_dp2_23p5_nside512.hdf5"
    original_flagship_mask: /global/cfs/cdirs/lsst/groups/PZ/users/qhang/desi-model-mask-nside-256.fits
    none: none

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: true
# where to put output logs for individual stages
log_dir: data/example/logs_desi_mocks
# where to put an overall parsl pipeline log
pipeline_log: data/example/log_desi_mocks.txt


# registry:
#     owner_type: project
#     owner: wlss-dp2-desi-delta-sigma
 