
# This larger run has nearly 79M galaxies in
#launcher: cori-mini

# These site options tell the launcher to use shifter
#site:
#    shifter: joezuntz/txpipe-dev

launcher: local
site: 
     max_threads: 1

modules: txpipe

stages:
    - name: TXSelector
      nprocess: 1
    - name: TXPhotozPlot
    - name: TXDiagnosticMaps
      nprocess: 1
    - name: TXRandomCat
      nodes: 1
    - name: TXTwoPoint
      nprocess: 1
      #nodes: 2
      threads_per_process: 64
    - name: TXTwoPointPlots
    - name: TXMapPlots
    - name: TXDiagnosticPlots
      nprocess: 1
    - name: TXGammaTBrightStars
      threads_per_process: 64
    - name: TXGammaTDimStars
      threads_per_process: 64
    - name: TXBrighterFatterPlot
    - name: TXRoweStatistics
      #nprocess: 2
      #nodes: 2
      #threads_per_process: 64
    - name: TXPSFDiagnostics

# Where to put outputs
output_dir: data/desy1/outputs


# configuration settings
config: examples/desy1/config_input_pz.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: /global/projecta/projectdirs/lsst/groups/WL/projects/wl-txpipe-hack/DESY1/shear_catalog_desy1_merged.h5
    photometry_catalog: /global/projecta/projectdirs/lsst/groups/WL/projects/wl-txpipe-hack/DESY1/photometry_catalog_desy1_merged.h5
    photoz_trained_model: data/desy1/inputs/cosmoDC2_trees_i25.3.npy
    calibration_table: data/desy1/inputs/sample_cosmodc2_w10year_errors.dat
    exposures: data/desy1/inputs/exposures.hdf5
    photoz_stack: data/desy1/outputs/photoz_stack.hdf5
    star_catalog: /global/projecta/projectdirs/lsst/groups/WL/projects/wl-txpipe-hack/DESY1/DES_psf_catalog.hdf5
    # This file comes with the code
    fiducial_cosmology: data/fiducial_cosmology.yml

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: True
# where to put output logs for individual stages
log_dir: data/desy1/logs
# where to put an overall parsl pipeline log
pipeline_log: data/desy1/log.txt

