TXSelector:
    input_pz: False
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    zbin_edges: [0.3, 0.7, 2.0]
    chunk_rows: 100000
    # Mag cuts
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

TXPhotozStack:
    chunk_rows: 100000

TXRandomCat:
    chunk_rows: 100000
    density: 10 # gals per sq arcmin

TXTwoPoint:
    binslop: 0.1
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 30 # our example is only 1x1 degrees
    nbins: 5
    verbose: 0

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 30 # our example is only 1x1 degrees
    nbins: 5
    pickled_wigner_transform: data/small/wigner.pkl


TXDiagnosticMaps:
    chunk_rows: 100000  # Number of rows to process at once
    sparse: True  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    pixelization: healpix
    nside: 1024
    # pixelization: gnomonic
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60
    depth_cut: 23.0


TXJackknifeCenters:
    npatch: 5
