# Stages to run
stages:
    - name: TXSourceSelector
    - name: TXLensSelector
    - name: TXPhotozStack
    - name: TXDiagnosticMaps
    - name: TXRandomCat
    - name: TXJackknifeCenters
    - name: TXTwoPoint
      threads_per_process: 2
    - name: TXDiagnosticPlots
    - name: TXGammaTFieldCenters
      threads_per_process: 2
    - name: TXGammaTBrightStars
      threads_per_process: 2
    - name: TXGammaTDimStars
      threads_per_process: 2
    - name: TXRoweStatistics
      threads_per_process: 2
    - name: TXTwoPointPlots
    - name: TXNullBlinding
    - name: TXRealGaussianCovariance
      threads_per_process: 2

# Where to put outputs
output_dir: data/small/outputs
launcher: local
site:
  max_threads: 1
modules: txpipe
config: examples/travis/config.yml

inputs:
    # See README for paths to download these files
    shear_catalog: data/small/shear_catalog.hdf5
    photometry_catalog: data/small/photometry_catalog.hdf5
    photoz_pdfs: data/small/photoz_pdfs.hdf5
    calibration_table: data/small/sample_cosmodc2_w10year_errors.dat
    exposures: data/small/exposures.hdf5
    star_catalog: data/small/star_catalog.hdf5

    # This file comes with the code
    fiducial_cosmology: data/fiducial_cosmology.yml

resume: False
log_dir: data/small/logs
pipeline_log: data/small/log.txt
