launcher: cori-mini

# If the launcher requires it (at the moment that is just for "cori")
# then this info is used to configure it.  Otherwise it is ignored
site:
    shifter: joezuntz/txpipe-dev

modules: txpipe


stages:
    - name: TXSelector
      nprocess: 32
    - name: PZPDFMLZ
      nprocess: 64
      nodes: 2
    - name: TXPhotozStack
      nprocess: 16
    - name: TXPhotozPlots
    - name: TXDiagnosticMaps
      nprocess: 8
    - name: TXRandomCat
    - name: TXTwoPoint
      nprocess: 2
      nodes: 2
      threads_per_process: 64
    - name: TXTwoPointPlots
    - name: TXMapPlots
    - name: TXDiagnosticPlots
      nprocess: 8
    - name: TXGammaTBrightStars
      threads_per_process: 64
    - name: TXGammaTDimStars
      threads_per_process: 64
    - name: TXBrighterFatterPlot
    - name: TXRoweStatistics
      nprocess: 2
      nodes: 2
      threads_per_process: 64
    - name: TXPSFDiagnostics

output_dir: cosmodc2-2.1i-outputs
config: test/config.yml





# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: cosmodc2-2.1i-inputs/shear_catalog.hdf5
    photometry_catalog: cosmodc2-2.1i-inputs/photometry_catalog.hdf5
    photoz_trained_model: cosmodc2-2.1i-inputs/cosmoDC2_trees_i25.3.npy
    fiducial_cosmology: test/fiducial_cosmology.yml
    calibration_table: cosmodc2-2.1i-inputs/sample_cosmodc2_w10year_errors.dat
    star_catalog: cosmodc2-2.1i-inputs/star_catalog.hdf5
    exposures: cosmodc2-2.1i-inputs/exposures.hdf5

resume: True
log_dir: cosmodc2-2.1i-outputs/logs
pipeline_log: log.txt

