TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/jsanch87/
    photo_dir: /global/cscratch1/sd/jsanch87/

TXMetacalGCRInput:
    cat_name: HSC_pdr1_wide_gama09h_shear

TXExposureInfo:
    dc2_name: '1.2p'


    #TXProtoDC2Mock:
    #cat_name: cosmoDC2_v1.1.4_image
    #extra_cols: redshift_true size_true shear_1 shear_2


PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000
    #bands: 'grizy'
TXPhotozStack:
    chunk_rows: 100000

TXSelector:
    bands: i #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    zbin_edges: [0.15, 0.5, 0.75, 1.0, 1.5]
    chunk_rows: 100000
    # Mag cuts
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 19.6
    i_lo_cut: 17.5
    i_hi_cut: 19.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

    #TXRandomCat:
    #chunk_rows: 100000
    #density: 10 # gals per sq arcmin

    #TXTwoPoint:
    #binslop: 0.1
    #delta_gamma: 0.02
    #do_pos_pos: True
    #do_shear_shear: True
    #do_shear_pos: True
    #flip_g2: True  # use true when using metacal shears
    #verbose: 0

TXDiagnosticMaps:
    chunk_rows: 100000  # Number of rows to process at once
    sparse: True  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    pixelization: healpix
    nside: 1024
    # pixelization: gnomonic
    # # 
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60


TXTwoPointFourier:
    chunk_rows: 100000
    flip_g2: False
    fiducial_cosmology: examples/cosmo_HSC.yml
