# Stages to run
stages:
    - name: TXSelector
    - name: PZPDFMLZ
    - name: TXPhotozStack
    - name: TXDiagnosticMaps
    - name: TXRandomCat
    - name: TXJackknifecenters
    - name: TXTwoPoint
    - name: TXDiagnosticPlots
    - name: TXGammaTFieldCenters
    - name: TXGammaTBrightStars
    - name: TXGammaTDimStars
    - name: TXRoweStatistics
    - name: TXTwoPointPlots

# Where to put outputs
output_dir: data/example/outputs

# How to run the pipeline (which site, e.g. cori, local=laptop)
launcher: local

# Information for the pipeline about how many jobs it can
# run and how it can do so
site:
  max_threads: 1

# python modules to import to search for stages
modules: txpipe

# configuration settings
config: examples/config.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: data/example/inputs/shear_catalog.hdf5
    photometry_catalog: data/example/inputs/photometry_catalog.hdf5
    photoz_trained_model: data/example/inputs/cosmoDC2_trees_i25.3.npy
    calibration_table: data/example/inputs/sample_cosmodc2_w10year_errors.dat
    exposures: data/example/inputs/exposures.hdf5
    star_catalog: data/example/inputs/star_catalog.hdf5
    #patch_centers: data/example/inputs/jackcenters.hdf5
    # This file comes with the code
    fiducial_cosmology: data/fiducial_cosmology.yml

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: False
# where to put output logs for individual stages
log_dir: data/example/logs
# where to put an overall parsl pipeline log
pipeline_log: data/example/log.txt
