global:
    pixelization: healpix

TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.1i_dr1b_with_metacal_griz

TXExposureInfo:
    dc2_name: '1.2p'

TXLSSWeightsUnit:
    nside: 2048
    pixelization: healpix

TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2 Mag_true_r_sdss_z0 
    flip_g2: True # to match metacal
    snr_limit: 4.0
    Mag_r_limit: -19
    unit_response: True
    apply_mag_cut: False

TXIngestRedmagic:
    lens_zbin_edges: [0.15, 0.3, 0.45, 0.6, 0.75, 0.9]

TXSourceTrueNumberDensity:
    name: TXSourceTrueNumberDensity
    nz: 601
    zmax: 3.0
    chunk_rows: 100000
    aliases:
        tomography_catalog: shear_tomography_catalog
        catalog: shear_catalog
        weights_catalog: shear_catalog
        photoz_stack: shear_photoz_stack
    weight_col: metacal/weight
    redshift_group: metacal

TXLensTrueNumberDensity:
    name: TXLensTrueNumberDensity
    nz: 601
    zmax: 3.0
    chunk_rows: 100000
    aliases:
        tomography_catalog: lens_tomography_catalog
        catalog: photometry_catalog
        weights_catalog: none
        photoz_stack: lens_photoz_stack
    redshift_group: photometry

TXLensMaps:
    chunk_rows:  100000
    pixelization: healpix
    nside: 2048
    sparse: True

TXSourceMaps:
    nside: 2048
    sparse: True
    chunk_rows:  100000
    pixelization: healpix
    true_shear: False

TXExternalLensMaps:
    nside: 2048
    sparse: True
    chunk_rows:  100000
    pixelization: healpix

TXExternalLensNoiseMaps:
    nside: 2048
    chunk_rows:  100000
    pixelization: healpix

TXAuxiliarySourceMaps:
    chunk_rows:  100000
    sparse:  True
    psf_prefix:  psf_

TXAuxiliaryLensMaps:
    chunk_rows:  100000
    sparse:  True
    nside: 2048
    pixelization: healpix
    sparse: True
    bright_obj_threshold:  22.0

TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 10.0        


PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXPhotozStack:
    chunk_rows: 100000

# Mock version of stacking:
TXTrueNumberDensity:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXSourceSelectorMetacal:
    input_pz: False
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.19285902, 0.40831394, 0.65503818, 0.94499109, 1.2947086, 1.72779632, 2.27855242, 3. ] # 7 bins
    # source_zbin_edges: [0.25588604, 0.55455363, 0.91863365, 1.38232001, 2.] # 4 bins
    chunk_rows: 100000
    true_z: False
    shear_prefix: mcal_

TXSourceSelectorMetadetect:
    input_pz: False
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.19285902, 0.40831394, 0.65503818, 0.94499109, 1.2947086, 1.72779632, 2.27855242, 3. ] # 7 bins
    # source_zbin_edges: [0.25588604, 0.55455363, 0.91863365, 1.38232001, 2.] # 4 bins
    chunk_rows: 100000
    true_z: False
    shear_prefix: ''


TXRandomCat:
    chunk_rows: 100000
    density: 10 # gals per sq arcmin

TXJackknifeCenters:
    npatch: 40

TXSourceDiagnosticPlots:
    shear_prefix: mcal_

TXFourierGaussianCovariance:
    galaxy_bias: [1.404, 1.458, 1.693, 1.922, 2.133] # Tinker bias values
    cache_dir: ./cache_nmt/cosmodc2/nside2048/

TXFourierTJPCovariance:
    galaxy_bias: [1.404, 1.458, 1.693, 1.922, 2.133] # Tinker bias values
    cache_dir: ./cache_nmt/cosmodc2/nside2048/
    IA: 0.

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 250.
    nbins: 20
    use_true_shear: False
    nprocess: 4
    threads_per_process: 2
    nodes: 4
    galaxy_bias: [1.404, 1.458, 1.693, 1.922, 2.133] # Tinker bias values

TXTwoPointFourier:
    chunk_rows: 100000
    flip_g1: True
    flip_g2: True
    apodization_size: 0.0
    cache_dir: ./cache_nmt/cosmodc2/nside2048/
    true_shear: False
    n_ell: 30
    ell_max: 6144 # nside * 3 , since Namaster computes that anyway. 
    nside: 2048
    analytic_noise: True
    
TXTwoPoint:
    bin_slop: 0.01
    delta_gamma: 0.02
    do_pos_pos: True
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: True  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    var_method: jackknife

   
TXClusteringNoiseMaps:
    n_realization: 30

TXLensingNoiseMaps:
    n_realization: 30

TXTruthLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0

TXPhotozPlotLens:
    name: TXPhotozPlotLens
    aliases:
        photoz_stack: lens_photoz_stack
        nz_plot: lens_nz

TXPhotozPlotSource:
    name: TXPhotozPlotSource
    aliases:
        photoz_stack: shear_photoz_stack
        nz_plot: source_nz
