global:
    pixelization: healpix
    chunk_rows: 1000000
    chunk_size: 200000

TXLSSWeightsUnit:
    nside: 2048
    pixelization: healpix

TXDiagnosticQuantiles:
    psf_prefix: mcal_psf_
    shear_prefix: mcal_
    nbins: 20

TXShearCalibration:
    shear_prefix: mcal_

TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2 Mag_true_r_sdss_z0
    flip_g2: true # to match metacal
    snr_limit: 4.0
    Mag_r_limit: -19
    unit_response: true
    apply_mag_cut: false

TXIngestRedmagic:
    lens_zbin_edges: [0.15, 0.3, 0.45, 0.6, 0.75, 0.9]

TXSourceTrueNumberDensity:
    name: TXSourceTrueNumberDensity
    nz: 601
    zmax: 3.0
    weight_col: metacal/weight
    redshift_group: metacal

TXLensTrueNumberDensity:
    name: TXLensTrueNumberDensity
    nz: 601
    zmax: 3.0
    redshift_group: photometry

TXLensMaps:
    pixelization: healpix
    nside: 2048
    sparse: true

TXSourceMaps:
    nside: 2048
    sparse: true
    pixelization: healpix
    true_shear: false

TXExternalLensMaps:
    nside: 2048
    sparse: true
    pixelization: healpix

TXExternalLensNoiseMaps:
    nside: 2048
    pixelization: healpix

TXAuxiliarySourceMaps:
    sparse: true
    psf_prefix: psf_

TXAuxiliaryLensMaps:
    sparse: true
    nside: 2048
    pixelization: healpix
    bright_obj_threshold: 22.0

TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 10.0



TXSourceSelectorMetacal:
    input_pz: false
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.19285902, 0.40831394, 0.65503818, 0.94499109, 1.2947086, 1.72779632, 2.27855242, 3.]  # 7 bins
    # source_zbin_edges: [0.25588604, 0.55455363, 0.91863365, 1.38232001, 2.] # 4 bins
    true_z: false
    shear_prefix: mcal_

TXSourceSelectorMetadetect:
    input_pz: false
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.19285902, 0.40831394, 0.65503818, 0.94499109, 1.2947086, 1.72779632, 2.27855242, 3.]  # 7 bins
    # source_zbin_edges: [0.25588604, 0.55455363, 0.91863365, 1.38232001, 2.] # 4 bins
    true_z: false
    shear_prefix: ''


TXRandomCat:
    density: 10 # gals per sq arcmin

TXJackknifeCenters:
    npatch: 40

TXSourceDiagnosticPlots:
    shear_prefix: mcal_

TXFourierGaussianCovariance:
    galaxy_bias: [1.404, 1.458, 1.693, 1.922, 2.133] # Tinker bias values
    cache_dir: ./cache_nmt/cosmodc2/nside2048/

TXFourierTJPCovariance:
    galaxy_bias: [1.404, 1.458, 1.693, 1.922, 2.133] # Tinker bias values
    cache_dir: ./cache_nmt/cosmodc2/nside2048/
    IA: 0.

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 250.
    nbins: 20
    use_true_shear: false
    galaxy_bias: [1.404, 1.458, 1.693, 1.922, 2.133] # Tinker bias values

TXTwoPointFourier:
    flip_g1: true
    flip_g2: true
    apodization_size: 0.0
    cache_dir: ./cache_nmt/cosmodc2/nside2048/
    true_shear: false
    n_ell: 30
    ell_max: 6144 # nside * 3 , since Namaster computes that anyway. 
    nside: 2048
    analytic_noise: true

TXTwoPoint:
    reduce_randoms_size: 0.5
    bin_slop: 0.01
    delta_gamma: 0.02
    do_pos_pos: true
    do_shear_shear: true
    do_shear_pos: true
    flip_g2: true  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    var_method: jackknife


TXLensNoiseMaps:
    clustering_realizations: 30

TXSourceNoiseMaps:
    lensing_realizations: 30


TXRandomForestLensSelector:
    verbose: false
    bands: ugrizy
    lens_zbin_edges: [0.2, 0.4, 0.6, 0.8, 1.0, 1.2]
    random_seed: 79521323
    mag_i_limit: 24.1
    selection_type: maglim


TXPhotozPlotLens:
    name: TXPhotozPlotLens
TXPhotozPlotSource:
    name: TXPhotozPlotSource


FlowCreator:
    n_samples: 1000000
    seed: 5763248


GridSelection:
    redshift_cut: 5.1
    ratio_file: data/example/inputs/hsc_ratios_and_specz.hdf5
    settings_file: data/example/inputs/HSC_grid_settings.pkl
    random_seed: 66
    pessimistic_redshift_cut: 1.0



PZRailSummarizeLens:
    leafsize: 20
    zmin: 0.0
    zmax: 3.0
    nzbins: 50
    name: PZRailSummarizeLens
    catalog_group: lens
    tomography_name: lens
    bands: ugrizy


PZRailSummarizeSource:
    leafsize: 20
    zmin: 0.0
    zmax: 3.0
    nzbins: 50
    mag_prefix: /shear/mcal_mag_
    tomography_name: source
    catalog_group: shear
    bands: riz
    name: PZRailSummarizeSource



PZPrepareEstimatorLens:
    name: PZPrepareEstimatorLens
    classname: BPZliteInformer
    zmin: 0.0
    zmax: 3.0
    nzbins: 301
    columns_file: ./data/bpz_ugrizy.columns
    data_path: ./data/example/rail-bpz-inputs
    spectra_file: CWWSB4.list
    prior_band: i
    ref_band: i
    # Not sure about this
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    mag_err_min: 0.005
    inform_options: {save_train: false, load_model: false, modelfile: BPZpriormodel.out}
    madau_reddening: no
    bands: riz
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    hdf5_groupname: photometry



PZEstimatorLens:
    name: PZEstimatorLens
    classname: BPZliteEstimator
    zmin: 0.0
    zmax: 3.0
    dz: 0.01
    nzbins: 301
    band_names: [mag_u, mag_g, mag_r, mag_i, mag_z, mag_y]
    bands: [mag_u, mag_g, mag_r, mag_i, mag_z, mag_y]
    err_bands: [mag_err_u, mag_err_g, mag_err_r, mag_err_i, mag_err_z, mag_err_y]
    hdf5_groupname: photometry
    nondetect_val: .inf
    columns_file: ./data/bpz_ugrizy.columns
    data_path: ./data/example/rail-bpz-inputs
    spectra_file: CWWSB4.list
    prior_band: mag_i
    ref_band: mag_i
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    mag_err_min: 0.005
    madau_reddening: false
    mag_limits:
        mag_u: 27.79
        mag_g: 29.04
        mag_r: 29.06
        mag_i: 28.62
        mag_z: 27.98
        mag_y: 27.05



TXParqetToHDF:
    hdf_group: photometry

NZDirInformerSource:
    name: NZDirInformerSource
    usecols: riz
    hdf5_groupname: photometry

NZDirInformerLens:
    name: NZDirInformerLens
    usecols: ugrizy
    hdf5_groupname: photometry
