launcher:
    name: mini
    interval: 3.0

site:
    name: local


modules: >
    txpipe
    rail.creation.degraders.photometric_errors
    rail.creation.degraders.quantityCut
    rail.creation.degraders.spectroscopic_degraders
    rail.creation.engines.flowEngine
    rail.estimation.algos.nz_dir
    rail.estimation.algos.bpz_lite

python_paths:
  - submodules/WLMassMap/python/desc/

stages:
  # Simulating spectroscopic sample
  - name: FlowCreator
    aliases:
        output: ideal_specz_catalog
        model: flow
  - name: LSSTErrorModel
    aliases:
        input: ideal_specz_catalog
        output: noisy_specz_catalog
  - name: InvRedshiftIncompleteness
    aliases:
        input: noisy_specz_catalog
        output: incomplete_specz_catalog
  - name: LineConfusion
    aliases:
        input: incomplete_specz_catalog
        output: confused_specz_catalog
  - name: QuantityCut
    aliases:
        input: confused_specz_catalog
        output: final_specz_catalog
  - name: TXParqetToHDF
    aliases:
        input: final_specz_catalog
        output: spectroscopic_catalog
  - name: TXSourceTomography
    threads_per_process: 8
  - name: TXSourceSelectorMetadetect
    # nprocess: 32
  - name: TXShearCalibration
    # nprocess: 32
  - name: PZPrepareEstimatorLens     # Prepare the p(z) estimator
    classname: BPZliteInformer
    aliases:
        input: spectroscopic_catalog
        model: lens_photoz_model

  - name: PZEstimatorLens
    classname: BPZliteEstimator
    # nprocess: 256
    # nodes: 2
    aliases:
        model: lens_photoz_model
        input: photometry_catalog
        output: lens_photoz_pdfs

  - name: NZDirInformerLens         # Prepare the DIR method inputs for the lens sample     
    classname: NZDirInformer
    aliases:
        input: spectroscopic_catalog
        model: lens_direct_calibration_model

  - name: PZRailSummarizeLens      # Run the DIR method on the lens sample to find n(z)
    classname: PZRailSummarize
    aliases:
        tomography_catalog: lens_tomography_catalog
        binned_catalog: binned_lens_catalog
        model: lens_direct_calibration_model
        photoz_stack: lens_photoz_stack
        photoz_realizations: lens_photoz_realizations


  - name: NZDirInformerSource       # Prepare the DIR method inputs for the source sample
    classname: NZDirInformer
    aliases:
        input: spectroscopic_catalog
        model: source_direct_calibration_model

  - name: PZRailSummarizeSource    # Run the DIR method on the lens sample to find n(z)
    classname: PZRailSummarize
    aliases:
        tomography_catalog: shear_tomography_catalog
        binned_catalog: binned_shear_catalog
        model: source_direct_calibration_model
        photoz_stack: shear_photoz_stack
        photoz_realizations: source_photoz_realizations


  - name: TXRandomCat
    # nprocess: 16
  - name: TXLSSWeightsUnit
  - name: TXRandomForestLensSelector
    # nprocess: 32
  - name: TXPhotozPlotSource
    classname: TXPhotozPlot
    aliases:
        photoz_stack: shear_photoz_stack
        nz_plot: source_nz
  - name: TXPhotozPlotLens
    classname: TXPhotozPlot
    aliases:
        photoz_stack: lens_photoz_stack
        nz_plot: lens_nz
  - name: TXLensCatalogSplitter
    # nprocess: 32
  - name: TXTwoPointFourier
    # nprocess: 8
    # nodes: 2
    # threads_per_process: 32
  - name: TXTwoPointTheoryFourier
  - name: TXTwoPointPlotsFourier
  - name: TXJackknifeCenters
  - name: TXSourceMaps
    # nprocess: 8
  - name: TXLensMaps
    # nprocess: 8
  - name: TXAuxiliarySourceMaps
    # nprocess: 8
  - name: TXAuxiliaryLensMaps
    # nprocess: 8
  - name: TXDensityMaps
  - name: TXSourceNoiseMaps
    # nprocess: 4
    # nodes: 1
    # threads_per_process: 1
  - name: TXLensNoiseMaps
    # nprocess: 4
    # nodes: 1
    # threads_per_process: 1
  - name: TXSimpleMask
  - name: TXMapPlots
  - name: TXTracerMetadata
  - name: TXNullBlinding
  - name: TXTwoPoint
    # threads_per_process: 32
    # nprocess: 8
    # nodes: 2
  - name: TXTwoPointPlotsTheory
  - name: TXDiagnosticQuantiles
    # nodes: 1
    # nprocess: 16
  - name: TXLensDiagnosticPlots
    # nprocess: 16
    # nodes: 1
  - name: TXSourceDiagnosticPlots
    # nprocess: 16
    # nodes: 1
  - name: TXFourierGaussianCovariance
    # threads_per_process: 32
  - name: TXTwoPointTheoryReal
  - name: TXRealGaussianCovariance
    # threads_per_process: 32
  - name: TXConvergenceMaps
    # threads_per_process: 32
  - name: TXConvergenceMapPlots

output_dir: data/cosmodc2/cutout-outputs
config: examples/cosmodc2/config.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: data/cosmodc2/cutout/example_shear_catalog.hdf5
    photometry_catalog: data/cosmodc2/cutout/example_photometry_catalog.hdf5
    fiducial_cosmology: data/fiducial_cosmology.yml
    none: none
    flow: data/example/inputs/example_flow.pkl

resume: true
log_dir: data/cosmodc2/logs
pipeline_log: data/cosmodc2/log.txt

