launcher:
    name: mini
    interval: 3.0

site:
    name: nersc-interactive
    image: ghcr.io/lsstdesc/txpipe

modules: txpipe

python_paths:
  - submodules/WLMassMap/python/desc/
  - submodules/FlexZPipe

stages:
  - name: TXRandomCat
    nprocess: 16
  - name: TXSourceSelectorMetacal
    nprocess: 32
  - name: TXRandomForestLensSelector
    nprocess: 32
  - name: TXLensTrueNumberDensity
    classname: TXTruePhotozStack
    aliases:
        tomography_catalog: lens_tomography_catalog
        catalog: photometry_catalog
        weights_catalog: none
        photoz_stack: lens_photoz_stack
  - name: TXSourceTrueNumberDensity
    classname: TXTruePhotozStack
    aliases:
        tomography_catalog: shear_tomography_catalog
        catalog: shear_catalog
        weights_catalog: shear_catalog
        photoz_stack: shear_photoz_stack
  - name: TXPhotozPlotSource
    classname: TXPhotozPlot
    aliases:
        photoz_stack: shear_photoz_stack
        nz_plot: source_nz
  - name: TXPhotozPlotLens
    classname: TXPhotozPlot
    aliases:
        photoz_stack: lens_photoz_stack
        nz_plot: lens_nz
  - name: TXShearCalibration
    nprocess: 32
  - name: TXTruthLensCatalogSplitter
    nprocess: 32
  - name: TXTwoPointFourier
    nprocess: 4
    nodes: 2
    threads_per_process: 32
  - name: TXTwoPointTheoryFourier
  - name: TXTwoPointPlotsFourier
  - name: TXJackknifeCenters
  - name: TXSourceMaps
    nprocess: 8
  - name: TXLensMaps
    nprocess: 8
  - name: TXAuxiliarySourceMaps
    nprocess: 8
  - name: TXAuxiliaryLensMaps
    nprocess: 8
  - name: TXDensityMaps
  - name: TXSourceNoiseMaps
    nprocess: 4
    nodes: 1
    threads_per_process: 1
  - name: TXLensNoiseMaps
    nprocess: 4
    nodes: 1
    threads_per_process: 1
  - name: TXSimpleMask
  - name: TXLSSWeightsUnit
  - name: TXMapPlots
  - name: TXTracerMetadata
  - name: TXNullBlinding
  - name: TXTwoPoint
    threads_per_process: 32
    nprocess: 2
    nodes: 2
  - name: TXTwoPointPlots
  - name: TXDiagnosticQuantiles
    nodes: 1
    nprocess: 16
  - name: TXLensDiagnosticPlots
    nprocess: 16
    nodes: 1
  - name: TXSourceDiagnosticPlots
    nprocess: 16
    nodes: 1
  - name: TXFourierGaussianCovariance
    threads_per_process: 32
  - name: TXTwoPointTheoryReal
  - name: TXRealGaussianCovariance
    threads_per_process: 32
  - name: TXConvergenceMaps
    threads_per_process: 32
  - name: TXConvergenceMapPlots

output_dir: data/cosmodc2/outputs
config: examples/cosmodc2/config.yml

# On NERSC, set this before running:
# export DATA=${LSST}/groups/WL/users/zuntz/data/metacal-testbed

inputs:
    # See README for paths to download these files
    shear_catalog: /global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/shear_catalog.hdf5
    photometry_catalog: /global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/photometry_catalog.hdf5
    photoz_trained_model: /global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/cosmoDC2_trees_i25.3.npy
    fiducial_cosmology: data/fiducial_cosmology.yml
    calibration_table: /global/cfs/cdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/sample_cosmodc2_w10year_errors.dat
    none: none

resume: true
log_dir: data/cosmodc2/logs
pipeline_log: data/cosmodc2/log.txt

