TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.2i_dr6c_with_metacal

TXExposureInfo:
    dc2_name: 1.2p

TXIngestStars:
    cat_name: dc2_object_run2.2i_dr6c

TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2
    flip_g2: true # to match metacal

FlexZPipe:
    has_redshift: false
    nz: 300
    metacal_fluxes: false
    chunk_rows: 100


PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000


TXPhotozPlotLens:
    name: TXPhotozPlotLens
TXPhotozPlotSource:
    name: TXPhotozPlotSource
TXTruePhotozStackSource:
    name: TXTruePhotozStackSource
    weight_col: metacal/weight
    redshift_group: metacal
    zmax: 2.0
    nz: 201

TXTruePhotozStackLens:
    name: TXTruePhotozStackLens
    redshift_group: photometry
    zmax: 2.0
    nz: 201


TXSourceTrueNumberDensity:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXSourceSelector:
    input_pz: false
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.3, 0.5, 0.7, 0.9, 2.0]
    chunk_rows: 100000
    # Mag cuts
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 19.6
    i_lo_cut: 17.5
    i_hi_cut: 19.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

TXRandomCat:
    chunk_rows: 100000
    density: 10 # gals per sq arcmin

TXTwoPoint:
    binslop: 0.1
    delta_gamma: 0.02
    do_pos_pos: true
    do_shear_shear: true
    do_shear_pos: true
    flip_g2: false  # False now seems to be right for metacal
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    subtract_mean_shear: true

TXSourceMaps:
    pixelization: healpix
    nside: 1024
    sparse: true

TXLensMaps:
    pixelization: healpix
    nside: 1024
    sparse: true


TXAuxiliarySourceMaps:
    chunk_rows: 100000
    sparse: true
    psf_prefix: psf_

TXAuxiliaryLensMaps:
    chunk_rows: 100000
    sparse: true
    bright_obj_threshold: 22.0

TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 30

TXSourceDiagnosticPlots:
    psf_prefix: mcal_psf_

TXLensDiagnosticPlots: {}

TXTwoPointFourier:
    chunk_rows: 100000
    flip_g2: true
    flip_g1: true
    bandwidth: 200
    apodization_size: 0.0
    cache_dir: ./cache


TXClusteringNoiseMaps:
    n_realization: 30

TXLensingNoiseMaps:
    n_realization: 30

TXMeanLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0, 0.2, 0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0

TXTruthLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0, 0.2, 0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0

