# Values in this section are accessible to all the different stages.
# They can be overridden by individual stages though.
global:
    # This is read by many stages that read complete
    # catalog data, and tells them how many rows to read
    # at once
    chunk_rows: 10000
    # These mapping options are also read by a range of stages
    pixelization: healpix
    nside: 256
    sparse: true  # Generate sparse maps - faster if using small areas

TXMatchSSI:
    name: TXMatchSSI
    match_radius: 0.1

TXMatchSSIMag:
    name: TXMatchSSIMag
    match_radius: 0.1
    magnification: 0.02
TXTruthLensSelectorSSI:
    name: TXTruthLensSelectorSSI
    # Mag cuts
    lens_zbin_edges: [0.0, 0.2, 0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
TXTruthLensSelectorSSIMag:
    name: TXTruthLensSelectorSSIMag
    # Mag cuts
    lens_zbin_edges: [0.0, 0.2, 0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
TXTruthLensCatalogSplitterSSI:
    name: TXTruthLensCatalogSplitterSSI
TXTruthLensCatalogSplitterSSIMag:
    name: TXTruthLensCatalogSplitterSSIMag
TXSSIMagnification:
    name: TXSSIMagnification
    applied_magnification: 1.02
