# Stages to run
stages:
  - name: TXIngestSSIDetectionDESBalrog
  - name: TXIngestSSIMatchedDESBalrog
  - name: TXAuxiliarySSIMaps
  - name: TXMapPlots

modules: txpipe

# Where to put outputs
output_dir: data/example/outputs_ssi_des_depth/

# How to run the pipeline: mini, parsl, or cwl
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2

# configuration settings
config: examples/ssi/config_ssi_depth.yml

inputs:
    # See README for paths to download these files
    
    #NERSC
    #balrog_detection_catalog: /global/cfs/cdirs/lsst/groups/WL/users/jelvinpo/balrog_txpipe_example/balrog_detection_catalog_sof_run2_v1.4.fits
    
    #local
    balrog_detection_catalog: /Users/jackelvinpoole/DES/cats/y3/balrog/balrog_detection_catalog_sof_run2a_v1.4.fits
    balrog_matched_catalog: /Users/jackelvinpoole/DES/cats/y3/balrog/balrog_matched_catalog_sof_run2a_v1.4.fits

    source_maps: None
    lens_maps: None
    density_maps: None
    mask: None
    aux_source_maps: None
    aux_lens_maps: none

    fiducial_cosmology: data/fiducial_cosmology.yml

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: false
# where to put output logs for individual stages
log_dir: data/example/outputs_ssi_des_mag/logs/
# where to put an overall parsl pipeline log
pipeline_log: data/example/outputs_ssi_des_mag/log.txt
