
# Stages to run
stages:
    - name: TXIngestSSIGCR


# modules and packages to import that have pipeline
# stages defined in them
modules: txpipe
# modules: txpipe rail tjpcov

# Where to put outputs
output_dir: data/example/outputs_ssi_gcr/

# How to run the pipeline: mini, parsl, or cwl
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2

# configuration settings
config: examples/ssi/config_gcr.yml

inputs:    
    fiducial_cosmology: data/fiducial_cosmology.yml

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: False
# where to put output logs for individual stages
log_dir: data/example/outputs_ssi_gcr/logs/
# where to put an overall parsl pipeline log
pipeline_log: data/example/outputs_ssi_gcr/log.txt
