global:
    chunk_rows: 1000000

TXGCRTwoCatalogInput:
    metacal_dir: 
        /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: 
        /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.1i_dr1b_with_metacal_griz

TXExposureInfo:
    dc2_name: 1.2p


TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2
    flip_g2: true # to match metacal

TXIngestRedmagic:
    lens_zbin_edges: [0.1, 0.3, 0.5, 0.7, 0.9]

TXSourceTrueNumberDensity:
    nz: 301
    zmax: 3.0
    name: TXSourceTrueNumberDensity
    aliases:
        tomography_catalog: shear_tomography_catalog
        catalog: shear_catalog
        weights_catalog: shear_catalog
        photoz_stack: shear_photoz_stack
    weight_col: shear/00/weight
    redshift_group: shear/00

# Mock version of stacking:
TXLensTrueNumberDensity:
    nz: 301
    zmax: 3.0
    name: TXLensTrueNumberDensity
    aliases:
        tomography_catalog: lens_tomography_catalog
        catalog: photometry_catalog
        weights_catalog: none
        photoz_stack: lens_photoz_stack
    redshift_group: photometry


TXLensMaps:
    pixelization: healpix
    nside: 512
    sparse: true

TXSourceMaps:
    nside: 512
    sparse: true
    pixelization: healpix
    true_shear: false

TXExternalLensMaps:
    nside: 512
    sparse: true
    pixelization: healpix


TXAuxiliarySourceMaps:
    sparse: true
    psf_prefix: psf_

TXAuxiliaryLensMaps:
    sparse: true
    bright_obj_threshold: 22.0

TXSimpleMask:
    depth_cut: 23.0
    bright_object_max: 10.0


PZPDFMLZ:
    nz: 301
    zmax: 3.0

TXPhotozStack: {}



TXSourceSelectorMetacal:
    input_pz: false
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.3, 0.55, 0.8, 1.05, 2.0]
    # may also need one for r_cpar_cut
    true_z: false
    shear_prefix: mcal_

TXRandomCat:
    density: 10 # gals per sq arcmin

TXJackknifeCenters:
    npatch: 40

TXSourceDiagnosticPlots:
    shear_prefix: mcal_

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 250.
    nbins: 20

TXTwoPoint:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: true
    do_shear_shear: true
    do_shear_pos: true
    flip_g2: true  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    use_true_shear: false

TXTwoPointLensCat:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: true
    do_shear_shear: true
    do_shear_pos: true
    flip_g2: true  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 250
    nbins: 20
    verbose: 0
    use_true_shear: false

TXTwoPointFourier:
    flip_g2: true
    flip_g1: true
    apodization_size: 0.0
    cache_dir: ./cache
    true_shear: false

TXClusteringNoiseMaps:
    n_realization: 30

TXLensingNoiseMaps:
    n_realization: 30

TXTruthLensSelector:
    # Mag cuts
    lens_zbin_edges: [0.0, 0.2, 0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0


TXPhotozPlotLens:
    name: TXPhotozPlotLens
    aliases:
        photoz_stack: lens_photoz_stack
        nz_plot: lens_nz

TXPhotozPlotSource:
    name: TXPhotozPlotSource
    aliases:
        photoz_stack: shear_photoz_stack
        nz_plot: source_nz
