BPZ_lite:
    aliases:
        model: source_photoz_model
        input: shear_catalog
        output: source_photoz_pdfs
    zmin: 0.0
    zmax: 3.0
    dz: 0.01
    nzbins: 301
    band_names: [mag_r, mag_i, mag_z]
    band_err_names: [mag_err_r, mag_err_i, mag_err_z]
    hdf5_groupname: /shear/00
    nondetect_val: .inf
    columns_file: ./data/bpz_riz.columns
    spectra_file: SED/CWWSB4.list
    prior_band: mag_i
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    zp_errors: [0.01, 0.01, 0.01]
    mag_err_min: 0.005
    madau_reddening: false
    mag_limits:
        mag_r: 29.06
        mag_i: 28.62
        mag_z: 27.98


TXSourceSelectorMetadetect:
    # change to False to use realistic selection based on riz
    true_z: True
    bands: riz   # used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.1, 3.0]
    shear_prefix: ""


# No options here
CLIngestRedmapper:
    cat_name: cosmoDC2_v1.1.4_redmapper_v0.8.1

CLClusterShearCatalogs:
    max_radius: 10.0  # Mpc
    redshift_criterion: mean
