name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:

    runs-on: ubuntu-latest

    container:
      image: joezuntz/txpipe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download test data
      run: |
        wget -O example.tar.gz  "https://portal.nersc.gov/cfs/lsst/txpipe/data/example.tar.gz"
        tar -zxvf example.tar.gz

    - name: Test with pytest
      run: |
        pytest txpipe

    - name: Run more pipelines
      run: |
        ceci examples/laptop_redmagic_pipeline.yml
        ceci examples/laptop_lensfit_pipeline.yml
        ceci examples/metadetect/pipeline.yml
        test -f data/example/outputs/shear_xi_plus.png
        test -f data/example/outputs_redmagic/shear_xi_plus.png
        test -f data/example/outputs_lensfit/shear_xi_plus.png

    - name: Show logs
      if: ${{ always() }}
      run: |
        tail -n +1 data/example/logs/*
        tail -n +1 data/example/logs_redmagic/*
        tail -n +1 data/example/logs_lensfit/*
        tail -n +1 data/example/logs_metadetect/*
