name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test_Auto_Installer:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            INSTALL_DEPS: sudo apt-get update && sudo apt-get -y install wget
          - os: macos-latest
            INSTALL_DEPS: brew update && brew install wget
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install wget
      run: ${{ matrix.INSTALL_DEPS }}

    - name: Run Auto-Install
      run: ./bin/install.sh

    - name: Test after auto-install
      run: |
        source ./conda/bin/activate
        ceci examples/metadetect/pipeline.yml
