name: Redmagic Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:

    runs-on: ubuntu-latest

    container:
      image: joezuntz/txpipe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download test data
      run: |
        wget -O example.tar.gz  "https://portal.nersc.gov/cfs/lsst/txpipe/data/example.tar.gz"
        tar -zxvf example.tar.gz

    - name: Run redmagic pipeline
      run: |
        ceci examples/redmagic/pipeline.yml
        test -f data/example/outputs_redmagic/shear_xi_plus.png

    - name: Show logs
      if: ${{ always() }}
      run: |
        tail -n +1 data/example/logs_redmagic/*
