# Values in this section are accessible to all the different stages.
# They can be overridden by individual stages though.
global:
    # This is read by many stages that read complete
    # catalog data, and tells them how many rows to read
    # at once
    chunk_rows: 100000
    # These mapping options are also read by a range of stages
    pixelization: healpix
    nside: 64
    sparse: true  # Generate sparse maps - faster if using small areas

TXGCRTwoCatalogInput:
    metacal_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/metacal_table_summary
    photo_dir: /global/cscratch1/sd/desc/DC2/data/Run2.2i/dpdd/Run2.2i-t3828/object_table_summary

TXMetacalGCRInput:
    cat_name: dc2_object_run2.1i_dr1b_with_metacal_griz

TXExposureInfo:
    dc2_name: 1.2p


TXCosmoDC2Mock:
    cat_name: cosmoDC2_v1.1.4_image
    visits_per_band: 16
    extra_cols: redshift_true size_true shear_1 shear_2
    flip_g2: true # to match metacal

TXIngestRedmagic:
    lens_zbin_edges: [0.1, 0.3, 0.5]

PZPDFMLZ:
    nz: 301
    zmax: 3.0



PZPrepareEstimatorSource:
    name: PZPrepareEstimatorSource
    classname: BPZliteInformer
    zmin: 0.0
    zmax: 3.0
    nzbins: 301
    columns_file: ./data/bpz_ugrizy.columns
    data_path: ./data/example/rail-bpz-inputs
    spectra_file: CWWSB4.list
    prior_band: i
    # This is the new name for prior_band I think
    ref_band: i
    # Not sure about this
    prior_file: hdfn_gen
    p_min: 0.005
    gauss_kernel: 0.0
    mag_err_min: 0.005
    inform_options: {save_train: false, load_model: false, modelfile: BPZpriormodel.out}
    madau_reddening: no
    bands: riz
    zp_errors: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    hdf5_groupname: photometry


# Mock version of stacking:
TXSourceTrueNumberDensity:
    nz: 301
    zmax: 3.0


TXSourceSelectorMetadetect:
    input_pz: false
    true_z: true
    bands: riz #used for selection
    T_cut: 0.5
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.5, 0.7, 0.9, 1.1, 2.0]
    shear_prefix: ''
TXRandomCat:
    density: 10 # gals per sq arcmin

TXTwoPoint:
    bin_slop: 0.1
    delta_gamma: 0.02
    do_pos_pos: false
    do_shear_shear: true
    do_shear_pos: false
    flip_g2: true  # use true when using metacal shears
    min_sep: 2.5
    max_sep: 60.0
    nbins: 10
    verbose: 0
    subtract_mean_shear: true

TXGammaTBrightStars: {}

TXGammaTDimStars: {}

TXGammaTRandoms: {}

TXGammaTFieldCenters: {}

TXBlinding:
    seed: 1972  ## seed uniquely specifies the shift in parameters
    Omega_b: [0.0485, 0.001] ## fiducial_model_value, shift_sigma
    Omega_c: [0.2545, 0.01]
    w0: [-1.0, 0.1]
    h: [0.682, 0.02]
    sigma8: [0.801, 0.01]
    n_s: [0.971, 0.03]
    b0: 0.95  ## we use bias of the form b0/g
    delete_unblinded: true

TXSourceDiagnosticPlots:
    psf_prefix: 00/mcal_psf_
    shear_prefix: 00/
    nbins: 20
    g_min: -0.01
    g_max: 0.01
    psfT_min: 0.2
    psfT_max: 0.28
    T_min: 0.01
    T_max: 2.1
    s2n_min: 1.25
    s2n_max: 300


TXDiagnosticMaps:
    sparse: true  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    # pixelization: gnomonic
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60
    depth_cut: 23.0
    psf_prefix: mcal_psf_

TXSourceMaps:
    sparse: true  # Generate sparse maps - faster if using small areas


TXMainMaps: {}

TXAuxiliarySourceMaps:
    flag_exponent_max: 8
    psf_prefix: psf_

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 60.
    nbins: 10
    pickled_wigner_transform: data/example/inputs/wigner.pkl

TXFourierTJPCovariance:
    cov_type: [FourierGaussianFsky]

TXJackknifeCenters:
    npatch: 5


TXTwoPointFourier:
    flip_g2: true
    ell_min: 30
    ell_max: 100
    bandwidth: 20
    cache_dir: ./cache/workspaces

TXSimpleMaskFrac:
    supreme_map_file: data/example/inputs/supreme_dc2_dr6d_v2_g_nexp_sum_1deg2.hs
    depth_cut: 23.5
    bright_object_max: 10.0

TXMapCorrelations:
    supreme_path_root: data/example/inputs/supreme
    outlier_fraction: 0.05
    nbin: 20



PZRailSummarizeSource:
    leafsize: 20
    zmin: 0.0
    zmax: 3.0
    nzbins: 50
    mag_prefix: /shear/00/mag_
    catalog_group: shear
    tomography_name: source
    bands: riz
    name: PZRailSummarizeSource

FlowCreator:
    n_samples: 1000000
    seed: 5763248
InvRedshiftIncompleteness:
    pivot_redshift: 0.8
GridSelection:
    redshift_cut: 5.1
    ratio_file: data/example/inputs/hsc_ratios_and_specz.hdf5
    settings_file: data/example/inputs/HSC_grid_settings.pkl
    random_seed: 66
    pessimistic_redshift_cut: 1.0




TXParqetToHDF:
    hdf_group: photometry
NZDirInformerSource:
    name: NZDirInformerSource
    usecols: [r, i, z]
    hdf5_groupname: photometry
PZRealizationsPlotSource:
    name: PZRealizationsPlotSource
TXPhotozPlotSource:
    name: TXPhotozPlotSource
